spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/rainsday
    username: sa
    password: 

