spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/rainsday
    username: sa
    password: 

openweather:
  api:
    url: http://api.openweathermap.org/data/2.5/forecast
    key: ace7577f413330c21eff60e4661e2c45